name: my First Workflow

on: push
jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v4
# Multi line command
        - name: List and Read file
          run: |
            echo "My first Github Action Job"
            ls
            cat README.md
        - name: Generate ASCII
          run: cowsay -f dragon "Run for cover, I am a DRAGON...RAWR" >> dragon.txt

        

        # - name: Welcome Message
        #   run: echo "My first Github Action Job"

        # - name: List Files
        #   run: ls

        # - name: Read file
        #   run: cat README.md
        
